TrajectoryPlannerROS:
  max_vel_x: 0.35
  min_vel_x: 0
  max_vel_y: 0.2
  min_vel_y: 0.1
  max_vel_theta: 0.4
  min_in_place_vel_theta: 0.2
  max_in_place_vel_theta: 0.3
  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  holonomic_robot: false
  meter_scoring: true

  yaw_goal_tolerance: 0.5
  xy_goal_tolerance: 0.3
  controller_frequency: 5
  controller_patience: 10.0
