TrajectoryPlannerROS:
  max_vel_x: 0.6
  min_vel_x: 0.3
  max_vel_y: 0.6
  min_vel_y: 0.3
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.7

  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  holonomic_robot: true
