robot_radius: 0.2
map_type: voxel
transform_tolerance: 0.5

obstacle_layer:
  enabled: true
  ostacle_range: 2.0
  raytrace_range: 1.0

  observation_sources: scan
  combination_method: 1

  scan:
    sensor_frame: laser
    data_type: LaserScan
    topic: scan
    marking: true
    clearing: true
    expected_update_rate: 10


inflation_layer:
  enabled: true
  inflation_radius: 0.2

static_layer:
  enabled: true
  map_topic: /map
