global_costmap:
  global_frame: /map
  robot_base_frame: base_link
  update_frequency: 7.0
  static_map: true
  publish frequency: 3
  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  always_send_full_costmap: true
